
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode
  namespace: demo
  labels:
    app: hellonode
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.hellonoded: semver:~1.3
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: hellonode
    spec:
      containers:
      - name: hello-node-container
        image: gcr.io/hanna-prinz/hellonode
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
          name: http
          protocol: TCP