---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-node-hello-world
  namespace: demo
  labels:
    app: gke-node-hello-world
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.hellonoded: semver:~1.3
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: gke-node-hello-world
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: gke-node-hello-world
    spec:
      containers:
      - name: hello-node-container
        image: eu.gcr.io/hanna-prinz/gke-node-hello-world:6601ec99cc444693c2a9ad8d8dea32ba6d665b17
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
