apiVersion: v1
kind: Service
metadata:
  name: gke-node-hello-world
  namespace: demo
  labels:
    app: gke-node-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: gke-node-hello-world