
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.hellonoded: semver:~1.3
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: hellonode
    containers:
    - name: hello-node-container
      image: gcr.io/hanna-prinz/hellonode
      imagePullPolicy: Always
      ports:
      - name: http-server
        containerPort: 3000
        name: http
        protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: hellonode
  labels:
    app: hellonode
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
    protocol: TCP
  selector:
    app: hellonode


